name: Release

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Setup vsce
        run: npm i -g @vscode/vsce
      - name: Package extension
        run: vsce package
      - name: Upload VSIC artifact
        uses: actions/upload-artifact@v2
        with:
          name: VSIC
          path: "*.vsix"
